-- 1. LYCEUM STATS SEED
INSERT INTO "LyceumStats" (
    id,
    name,
    "nameEn",
    "addressUk",
    "addressEn",
    email,
    phone,
    "logoPhoto",
    "quoteUk",
    "quoteEn",
    "teachingLanguage",
    "teachingLanguageEn",
    specialization,
    "specializationEn",
    "anthemUrl",
    "teachersPhoto",
    "materialBasePhoto",
    "materialBaseDescriptionUk",
    "materialBaseDescriptionEn",
    "socialLinks",
    "studentsCount",
    "studentsCountReal",
    "teachersCount",
    "staffCount",
    "classesCount",
    "flexParticipants",
    "topScorersCount",
    "createdAt",
    "updatedAt"
)
VALUES (
           1,
           'Науковий ліцей',
           'Science Lyceum',
           'вул. Науки, 15',
           '15 Nauky St',
           'lyceum@edu.ua',
           '+380000000000',
           'https://example.com/logo.png',
           'Знання — це сила',
           'Knowledge is power',
           'Українська',
           'Ukrainian',
           'Математика',
           'Mathematics',
           'https://youtube.com/anthem',
           'https://example.com/teachers.jpg',
           'https://example.com/material.jpg',
           'Опис матеріально-технічної бази',
           'Description of the material and technical base',
           jsonb_build_object(
                   'facebook', 'https://fb.com/lyceum',
                   'instagram', 'https://inst.com/lyceum',
                   'youtube', 'https://yt.com/lyceum'
           ),
           650,
           651,
           54,
           20,
           24,
           12,
           18,
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP
       )
    ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
                            "nameEn" = EXCLUDED."nameEn",
                            "addressUk" = EXCLUDED."addressUk",
                            "addressEn" = EXCLUDED."addressEn",
                            email = EXCLUDED.email,
                            phone = EXCLUDED.phone,
                            "logoPhoto" = EXCLUDED."logoPhoto",
                            "quoteUk" = EXCLUDED."quoteUk",
                            "quoteEn" = EXCLUDED."quoteEn",
                            "teachingLanguage" = EXCLUDED."teachingLanguage",
                            "teachingLanguageEn" = EXCLUDED."teachingLanguageEn",
                            specialization = EXCLUDED.specialization,
                            "specializationEn" = EXCLUDED."specializationEn",
                            "anthemUrl" = EXCLUDED."anthemUrl",
                            "teachersPhoto" = EXCLUDED."teachersPhoto",
                            "materialBasePhoto" = EXCLUDED."materialBasePhoto",
                            "materialBaseDescriptionUk" = EXCLUDED."materialBaseDescriptionUk",
                            "materialBaseDescriptionEn" = EXCLUDED."materialBaseDescriptionEn",
                            "socialLinks" = EXCLUDED."socialLinks",
                            "studentsCount" = EXCLUDED."studentsCount",
                            "studentsCountReal" = EXCLUDED."studentsCountReal",
                            "teachersCount" = EXCLUDED."teachersCount",
                            "staffCount" = EXCLUDED."staffCount",
                            "classesCount" = EXCLUDED."classesCount",
                            "flexParticipants" = EXCLUDED."flexParticipants",
                            "topScorersCount" = EXCLUDED."topScorersCount",
                            "updatedAt" = CURRENT_TIMESTAMP;

-- 2. ADMIN USER SEED
INSERT INTO "AdminUser" (
    username,
    password,
    role,
    "isActive",
    "createdAt",
    "updatedAt"
)
VALUES (
           'european_admin',
           '$2a$12$48jjpVTAXKJl1IVvXrDsBek8pSQYyfpzqOsmmaEEVazhwn40j6yVm',
           'admin',
           true,
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP
       )
    ON CONFLICT (username) DO UPDATE SET
    role = EXCLUDED.role,
                                  "isActive" = EXCLUDED."isActive",
                                  "updatedAt" = CURRENT_TIMESTAMP;